name: Linux Shell Gang

on:
  push:
    tags:
      - 'l*'

jobs:
  Heeho:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Script time
        run: ./do.sh $(which bash)