name: Windows Shell Gang

on:
  push:
    tags:
      - 'w*'

jobs:
  Heeho:
    runs-on: macos-latest
    steps:
      - name: Get repository & do
        uses: actions/checkout@v2
        run: .\win.ps1
        shell: powershell